# Generated by Django 2.2.7 on 2019-12-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do departamento.', max_length=100, verbose_name='Departamento')),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
    ]
