# Generated by Django 2.2.7 on 2019-12-05 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_auto_20191205_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='colaboradores.Colaborador'),
            preserve_default=False,
        ),
    ]
