# Generated by Django 2.2.7 on 2019-12-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(help_text='Nome completo', max_length=150, verbose_name='Colaborador'),
        ),
    ]
