# Generated by Django 2.2.7 on 2019-12-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoraExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(help_text='motivo da hora extra', max_length=150, verbose_name='Motivo')),
            ],
            options={
                'verbose_name_plural': 'Registro de Horas Extras',
            },
        ),
    ]
