# Generated by Django 2.2.7 on 2019-12-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(help_text='ex: FSP Sistemas LTDA.', max_length=150, verbose_name='Nome da Empresa'),
        ),
    ]
